config/routes.rb
Rails.application.routes.draw do
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/algolia_searchable.rb
module AlgoliaSearchable
  include AlgoliaSearch
  extend ActiveSupport::Concern

  SEARCH_INDEX_SETTINGS = {
     auto_index: false,
     auto_remove: false,
     id: :search_id,
     if: :search_indexable?,
     index_name: "plants", # checkout out the index at https://www.algolia.com/explorer
     per_environment: true, # this means you will have a "plant_development" index when you run one of your rake tasks!
     sanitize: true
   }

   # attributes accessible on models
   SEARCH_ATTRIBUTES = [
     :name,
     :symbol
   ]

   # https://www.algolia.com/doc/api-client/ruby/parameters#attributestoindex
   SEARCH_ATTRIBUTES_TO_INDEX = [
     'name',
     'symbol'
   ]

   # https://www.algolia.com/doc/api-client/ruby/parameters#attributestoretrieve
   SEARCH_ATTRIBUTES_TO_RETRIEVE = [
     'name',
     'symbol'
   ]

  included do
    algoliasearch AlgoliaSearchable::SEARCH_INDEX_SETTINGS do
      attribute AlgoliaSearchable::SEARCH_ATTRIBUTES
      attributesToIndex AlgoliaSearchable::SEARCH_ATTRIBUTES_TO_INDEX
      attributesToRetrieve AlgoliaSearchable::SEARCH_ATTRIBUTES_TO_RETRIEVE
    end
  end

  def search_id
    "Plant_#{id}"
  end

  def search_indexable?
    # only add to the index records which have a name and a symbol and an id
    name && symbol && id ? true : false
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  include AlgoliaSearchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:abbreviation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantSearcherApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_for(plant) do |f| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abbreviation %>
    <%= f.text_field :abbreviation %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th>Abbreviation</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.abbreviation %></td>
        <td><%= plant.name %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abbreviation:</strong>
  <%= @plant.abbreviation %>
</p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>